### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by kbejnar** [LewisArdern/eslint-plugin-angularjs-security-rules#4]
Hi Lewis,  I've been pulling the package directly from Github for a while to benefit from some of the recent commits that have been made in it.  Could you publish a new version to NPM so I could switch over to using that?

**Comment by LewisArdern** [comment]
Hey! Yes, I will publish to npm.

**Comment by LewisArdern** [comment]
Published, bumped to 1.0.7 :) 

Please let me know if you encounter any issues.
